# (generated with --quick)

import pathlib
from typing import List, Tuple, Type

CONFIG_FILE_PATH: str
CONF_HOME: str
Path: Type[pathlib.Path]
configparser: module
os: module

class ConfigHandler:
    __doc__: str
    @staticmethod
    def _get_config_parser() -> configparser.ConfigParser: ...
    def get_plugin_entries(self) -> List[Tuple[str, configparser.SectionProxy]]: ...
    def get_plugin_install_location(self) -> str: ...
    def get_plugins(self) -> List[str]: ...
    @staticmethod
    def init_conf_dir() -> None: ...
    def init_conf_file(self) -> None: ...
    def write_plugin_to_conf(self, name: str, url: str) -> None: ...
